# Generated by Django 2.0.1 on 2019-06-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_auto_20190627_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='total',
        ),
    ]
