# Generated by Django 2.0.1 on 2019-06-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_remove_venda_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total R$'),
        ),
    ]
