# Generated by Django 2.0.1 on 2019-06-28 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_auto_20190627_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
