# Generated by Django 2.0.1 on 2019-07-01 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_auto_20190627_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['first_name'], 'permissions': (('list_clients', 'Usuário que pode ver a lista de clientes'),), 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
    ]
