# Generated by Django 2.0.1 on 2019-06-28 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0012_auto_20190627_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7, verbose_name='Número')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Total R$')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desconto R$')),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Impostos R$')),
                ('nfe_issued', models.BooleanField(default=False)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.Person', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['number'],
            },
        ),
    ]
