# Generated by Django 2.0.1 on 2019-06-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20190627_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total R$'),
        ),
    ]
