# Generated by Django 2.0.1 on 2019-06-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20190627_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantities',
            field=models.FloatField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto R$'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Impostos R$'),
        ),
    ]
