# Generated by Django 2.0.1 on 2019-07-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20190627_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['number'], 'permissions': (('setar_nfe', 'Usuário pode alterar parametro NF-e'),), 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
