# Generated by Django 2.0.1 on 2019-07-01 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0007_auto_20190701_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['number'], 'permissions': (('setar_nfe', 'Usuário pode alterar parametro NF-e'), ('ver_dash', 'Usuário que podem acessar a dashboard')), 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
