# Generated by Django 2.0.1 on 2019-07-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0009_auto_20190708_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('OP', 'Aberta'), ('CL', 'Fechada'), ('PC', 'Processando'), ('UN', 'Desconhecid0')], default='UN', max_length=2, verbose_name='Status da Venda'),
        ),
    ]
