# Generated by Django 2.0.1 on 2019-06-28 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20190627_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='vendas.Sale', verbose_name='Venda'),
        ),
    ]
