# Generated by Django 2.0.1 on 2019-06-28 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20190627_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sale',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
